//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookEdition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookEdition()
        {
            this.BookItems = new HashSet<BookItem>();
            this.Authors = new HashSet<Author>();
        }
    
        public string Isbn { get; set; }
        public int TitleId { get; set; }
        public Nullable<short> Edition { get; set; }
        public Nullable<short> Year { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<short> Review { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string AmazonUrl { get; set; }
    
        public virtual BookTitle BookTitle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookItem> BookItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Author> Authors { get; set; }
    }
}
