//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookItem
    {
        public int Id { get; set; }
        public string Isbn { get; set; }
        public short EbookTypeId { get; set; }
        public string FilePath { get; set; }
    
        public virtual BookEdition BookEdition { get; set; }
        public virtual EbookType EbookType { get; set; }
    }
}
