//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookTitle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookTitle()
        {
            this.BookEditions = new HashSet<BookEdition>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public short BookTopicId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookEdition> BookEditions { get; set; }
        public virtual BookTopic BookTopic { get; set; }
    }
}
